package com.protectcord.strata.migrate.converter;

import com.protectcord.strata.migrate.report.MigrationReport;
import com.protectcord.strata.migrate.terra.TerraPackData;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Assembles converted Terra components into a complete Strata profile directory.
 */
public final class ProfileAssembler {

    private static final Logger LOGGER = Logger.getLogger("Strata-Migrate");

    private final BiomeConverter biomeConverter = new BiomeConverter();
    private final NoiseConverter noiseConverter = new NoiseConverter();
    private final PaletteConverter paletteConverter = new PaletteConverter();

    /**
     * Converts an entire Terra pack to a Strata profile.
     *
     * @param packData   parsed Terra pack data
     * @param outputDir  output directory for the Strata profile
     * @param profileName  name for the generated profile
     * @return migration report
     */
    public MigrationReport assemble(TerraPackData packData, Path outputDir, String profileName)
            throws IOException {
        MigrationReport report = new MigrationReport();

        LOGGER.info("Converting Terra pack '" + packData.packId() + "' to Strata profile '" + profileName + "'");

        // Create directory structure
        Path biomesDir = outputDir.resolve("biomes");
        Path noiseDir = outputDir.resolve("noise");
        Path surfaceDir = outputDir.resolve("surface");
        Files.createDirectories(biomesDir);
        Files.createDirectories(noiseDir);
        Files.createDirectories(surfaceDir);

        // Generate profile.toml
        String profileToml = generateProfileToml(packData, profileName);
        Files.writeString(outputDir.resolve("profile.toml"), profileToml);
        report.addConverted("profile.toml");

        // Convert biomes
        for (Map<String, Object> biome : packData.biomes()) {
            try {
                String toml = biomeConverter.convert(biome, report);
                String id = getString(biome, "id", "unknown").toLowerCase().replace("-", "_");
                Files.writeString(biomesDir.resolve(id + ".toml"), toml);
            } catch (Exception e) {
                String id = getString(biome, "id", "unknown");
                report.addError("Failed to convert biome " + id + ": " + e.getMessage());
            }
        }

        // Convert noise functions
        for (Map<String, Object> noise : packData.noises()) {
            try {
                String toml = noiseConverter.convert(noise, report);
                String id = getString(noise, "id", "unknown").toLowerCase().replace("-", "_");
                Files.writeString(noiseDir.resolve(id + ".toml"), toml);
            } catch (Exception e) {
                String id = getString(noise, "id", "unknown");
                report.addError("Failed to convert noise " + id + ": " + e.getMessage());
            }
        }

        // Convert palettes to surface rules
        for (Map<String, Object> palette : packData.palettes()) {
            try {
                String toml = paletteConverter.convert(palette, report);
                String id = getString(palette, "id", "unknown").toLowerCase().replace("-", "_");
                Files.writeString(surfaceDir.resolve(id + ".toml"), toml);
            } catch (Exception e) {
                String id = getString(palette, "id", "unknown");
                report.addError("Failed to convert palette " + id + ": " + e.getMessage());
            }
        }

        // Flag unsupported items
        for (Map<String, Object> structure : packData.structures()) {
            report.addApproximated("structure." + getString(structure, "id", "unknown"),
                    "Structure conversion is approximate; manual tuning recommended");
        }

        if (!packData.carvers().isEmpty()) {
            report.addApproximated("carvers",
                    "Carver parameters were approximated; test in-game and adjust");
        }

        // Write migration report
        Files.writeString(outputDir.resolve("MIGRATION_REPORT.txt"), report.toText());

        LOGGER.info("Migration complete. Report written to " + outputDir.resolve("MIGRATION_REPORT.txt"));
        return report;
    }

    private String generateProfileToml(TerraPackData packData, String profileName) {
        return """
                # ============================================================
                # Strata World Profile - Converted from Terra pack: %s
                # ============================================================
                # This profile was automatically generated by Strata's Terra migration tool.
                # Review the MIGRATION_REPORT.txt for conversion notes.

                name = "%s"
                description = "Converted from Terra pack: %s"
                author = "%s"

                [terrain]
                sea-level = 63
                min-y = -64
                max-y = 320

                [water]
                [water.rivers]
                enabled = true

                [water.oceans]
                enabled = true
                """.formatted(packData.packId(), profileName, packData.packId(), packData.author());
    }

    private static String getString(Map<?, ?> map, String key, String defaultValue) {
        Object val = map.get(key);
        return val != null ? val.toString() : defaultValue;
    }
}
